
tenants:
  - name: Customer Name
    domain: bilanc.co
    is_auto_onboarding_enabled: true
    seats: 70
    taps:
      - name: github
        type: tap-github
        config:
          start_date: 2025-01-01
          access_token: !ENV ${GITHUB_ACCESS_TOKEN}
          repository: !ENV ${GITHUB_REPOSITORY}
      - name: linear
        type: tap-linear
        config:
          start_date: 2025-01-01
          access_token: !ENV ${LINEAR_ACCESS_TOKEN}
